### ISSUE TITLE
Running this library under IIS7 & ASP.NET 4.0

### ISSUE THREAD

**Issue by axerosolutions** [pruiz/WkHtmlToXSharp#10]
Hi,

I read in an earlier issue that running this lib under IIS is not supported. What does this imply? I would like to use this library, and get rid of AbcPdf in my ASP.NET 4.0 project. Is it possible? I do not want to use any web service or windows service.

Can I use it on a 64bit OS with IIS7 app pool set to 32-bit? If yes (as per your readme) then why did you mention here that IIS is not supported: https://github.com/pruiz/WkHtmlToXSharp/issues/8#issuecomment-7548939

Thank you,

Vivek

**Comment by pruiz** [comment]
Running this library under ASP.NET (or more specifically IIS) is not supported. This has to do with the way IIS manages underlaying threads, and application pools.

What most people do (myself included) is to create a daemon or windows service which handles requests from the ASP.NET/MVC/etc. process via any form of RPC or queuing.

Regards

**Comment by liguobao** [comment]
why IIS  will recycle the WkHtmlToXSharp memory?

I can‘t understand it.

**Comment by pruiz** [comment]
Try googling about it: https://www.outsystems.com/forums/discussion/10307/understanding-application-pool-recycling-and-how-to-fine-tune-for-use-with-outsys/

**Comment by liguobao** [comment]
Thanks.

**Comment by liguobao** [comment]
If the binary throw exception: “Attempted to read or write protected memory. This is often an indication that other memory is corrupt.” in IIS,we should restart the app to recycle bad memory?
