### ISSUE TITLE
x64 Support

### ISSUE THREAD

**Issue by samkelleher** [pruiz/WkHtmlToXSharp#12]
In the readme, you wrote that an x64 compile of WkHtmlToPdf  'worked pretty flawlessly'; was there anything broken/preventative from using this in a x64 environment if it worked?

Or was it just convenience, i.e., to be able to just drop in the WkHtmlToPdf  lib as built rather than go off and recompile in x64.

**Comment by pruiz** [comment]
I am closing this issue, as x64 support has been available for a while now.
