### ISSUE TITLE
Converting HTML string to PDF - output is unformatted

### ISSUE THREAD

**Issue by flurg** [pruiz/WkHtmlToXSharp#18]
When I pass a Page from the Internet, it works perfectly and converts the HTML exactly as the page looks. My requirements however mean I need to pass it a string of HTML so I'm using Convert(ValidHtmlString) instead of setting a Page and just calling Convert().

When I pass in my HTML string, it's outputting a PDF, but it's completely unformatted. It even outputs my CSS style declarations. For example, here's the beginning of one of my PDF outputs:

body { font-family: Arial; font-size: 14px; width: 796px; } #letterLeft { width: 45%; padding-left: 7%; float: left; } #letterRight { width: 34%;
float: left; padding-top: 20px; padding-left: 8%; } .GreenBox { margin-top: -8px; background-color: #D7E4BD; padding: 20px; width:
65%; border-radius: 10px; } .GreenBoxWide { margin-top: -8px; background-color: #D7E4BD; padding: 20px; width: 82%; borderradius:
10px; } .title { font-size: 1.2em; font-weight: bold; } .normal { font-size: 12px; font-weight: normal; } .subtext { font-size: 0.8em; }
.icon { float: left; padding-right: 15px; } .floatRight { float: right; } Working in partnership with

Does anyone have any idea why this may be happening? Have I missed a setting somewhere? Here is my code for the converter:

public class ConvertToPDF
    {
        private bool ConvertComplete { get; set; }
 
        public byte[] HtmlToPdf(string html)
        {
            using (var toPdf = GetConverter())
            {
                toPdf.GlobalSettings.Margin.Top = "1cm";
                toPdf.GlobalSettings.Margin.Bottom = "1cm";
                toPdf.GlobalSettings.Margin.Left = "1cm";
                toPdf.GlobalSettings.Margin.Right = "1cm";
 
                toPdf.ObjectSettings.Web.EnablePlugins = false;
                toPdf.ObjectSettings.Web.EnableJavascript = false;
                toPdf.ObjectSettings.Load.Proxy = "none";
 
                byte[] pdfBytes = toPdf.Convert(html);
 
                if (pdfBytes != null && ConvertComplete)
                {
                    return pdfBytes;
                }
                else
                {
                    return null;
                }
            }
        }
 
        private MultiplexingConverter GetConverter()
        {
            var obj = new MultiplexingConverter();
            obj.Finished += new EventHandler<EventArgs<bool>>(obj_Finished);
 
            return obj;
        }
 
        void obj_Finished(object sender, EventArgs<bool> e)
        {
            ConvertComplete = true;
        }   
    }

Thanks in advance.

**Comment by pruiz** [comment]
Current release uses a more modern wkhtmltopdf native version, so I am closing this issue.
