### ISSUE TITLE
Explain please the following test case: CanHandleAuthFailure

### ISSUE THREAD

**Issue by eugentorica** [pruiz/WkHtmlToXSharp#23]
Now this test case is not run (ignored) with the following attribute:
//[Ignore("This test requires (still to be released) wkhtmltopdf v0.12+")]
I have a couple of questions:
1) What is expected result for this case? Why it is considered that tmp should be not null?
2) What functionality fo v0.12 is necessary for this case to work correctly.

Thank you all in advance.

**Comment by pruiz** [comment]
I've just tested this on win32 & win64 as part of a pre-release cycle and it works just fine. I am closing this, but please re-open if it keeps failing on your side.
