### ISSUE TITLE
Wrong Common.Logging version in latest nuget package

### ISSUE THREAD

**Issue by aykutaras** [pruiz/WkHtmlToXSharp#26]
Hi,

There is a problem in your latest nuget package 1.1.23.22. In this package's Dependencies it says and installs Common.Logging 2.0.0 but inside dll you are using 2.1.0. Can you update dependency please. Because any time someone downloads this package, they will get the same error.

**Comment by Dbuggerx** [comment]
:+1:  I'm having this problem

**Comment by aykutaras** [comment]
@Dbuggerx  This library seem dead for 9 months. We moved from this dlls to impelementing a way to use original exe files. It resulted much better

**Comment by pruiz** [comment]
Closing as obsolete.
