### ISSUE TITLE
First-chance exception at 0x000007FEFDAF940D (KernelBase.dll) in w3wp.exe

### ISSUE THREAD

**Issue by JamesYing** [pruiz/WkHtmlToXSharp#28]
First-chance exception at 0x000007FEFDAF940D (KernelBase.dll) in w3wp.exe: 0xE0434352 (parameters: 0xFFFFFFFF80004003, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x000007FEF8D90000).

If there is a handler for this exception, the program may be safely continued.

I use WK in my project.The first convert is error,the second show this exception,How can I do?

**Comment by pruiz** [comment]
As stated on other issues (related to IIS), using this library from within IIS is not supported due to limitations with the underlaying wkhtmltopdf component.
