### ISSUE TITLE
WkHtmlToXSharp 1.2.9 nuget package missing

### ISSUE THREAD

**Issue by tomdenny** [pruiz/WkHtmlToXSharp#35]
It looks like version 1.2.9 of WkHtmlToXSharp didn't make it to nuget.  Since that's a dependency of all of the other packages, they error out when trying to install them.

**Comment by pruiz** [comment]
Sorry, I dont fully understand what you mean.

May you provide some context or an error message from Nuget package tools or something?

**Comment by tomdenny** [comment]
Sure.  On nuget, the [WkHtmlToXSharp package](https://www.nuget.org/packages/WkHtmlToXSharp/) is version **1.1.23.22** and says it was last updated in 2014.  

All of the other WkHtmlToXSharp packages, like [WkHtmlToXSharp.Win32](https://www.nuget.org/packages/WkHtmlToXSharp.Win32/), are version **1.2.9** and say they were last updated in 2015.  These packages depend on WkHtmlToXSharp ≥ 1.2.9 which doesn't exist on nuget. 

If you try to install WkHtmlToXSharp.Win32 you receive this error message:
```
install-package wkhtmltoxsharp.win32
Attempting to resolve dependency 'WkHtmlToXSharp (≥ 1.2.9)'.
install-package : Unable to resolve dependency 'WkHtmlToXSharp (≥ 1.2.9)'.
At line:1 char:1
+ install-package wkhtmltoxsharp.win32
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

**Comment by pruiz** [comment]
Looks like nuget publishing got stuck.. I've recently moved building of
wkhtmltoxsharp over to appVeyor, so I guess some tweaking will be required.

**Comment by pruiz** [comment]
Version 1.2.22 has been prublished (all packages this time) to nuget.
