### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by nicholasguyett** [pruiz/WkHtmlToXSharp#38]
Hi Pablo, I noticed this project hasn't been updated recently and wanted to know how much you intend to keep this project (and the associated NuGet package) up to date with the original library.

**Comment by pruiz** [comment]
We are still using this package, so I do intend on maintaining this project
alive (albeit not as high priority), and also I am willing to accept PRs
(if/when those PRs aling with proyect's styling and goals).

However, upgrading to newer wkhtmltox native libraries' version has proven
risky in the past, with new bugs and issues arising. So I tend to only
upgrade when I am quite confident on new version's stability. Given the
end-user can provide it's own wkhtmltox native libraries (or even create
his own bundle and register it during initialization) this has not been an
issue.. (until now?).

Cheers

**Comment by nicholasguyett** [comment]
Thank you very much.  I understand, just wanted to be certain this was being maintained.
