### ISSUE TITLE
Getting intermittent error that shuts down app pool

### ISSUE THREAD

**Issue by nicholasguyett** [pruiz/WkHtmlToXSharp#40]
Intermittently we're getting an exception from the queue thread that results in the entire IIS app pool shutting down.  We're using the `MultiplexingConverter` in response to an HTTP call.

Unfortunately, the exception is happening somewhere we can't wrap in a `try {} catch{}` block so the information we can provide is limited.  We were also unable to try catching the error by attaching the debugger to the source project.

Exception message:
```
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
mscorlib is microsoft dll
```

Thread: `WkHtmlToPdf Queue Thread: 1`

Any assistance or direction you can provide would be greatly appreciated.

**Comment by pruiz** [comment]
Please see: https://github.com/pruiz/WkHtmlToXSharp/issues/30 and https://github.com/pruiz/WkHtmlToXSharp/issues/10
