### ISSUE TITLE
Question regarding usage of MultiplexingConverter

### ISSUE THREAD

**Issue by JulianMay** [pruiz/WkHtmlToXSharp#45]
Hi!
We're trying to replace existing (buggy) WkHtml-integration with WkHtmlToXSharp. We're using it to generate reports of many different kinds, each report-generation running in a seperate thread with a prioritized queue in front.

I'm a bit confused, by the following (probably misunderstood) things, that maybe you can clear up:
* MultiplexingConverter can be re-used across streams for "concurrent-ish" generation
* report-specific options (GlobalSettings and ObjectSettings) cannot be injected on the Convert(...) method, but only set on the properties on the MultiplexingConverter
... This means it becomes a race-condition for pdf-generation for a given report to use the correct Global-/Object-settings
* I could instantiate a seperate WkHtmlToPdfConverter instance per report, but I read in another issue that repeated instantiation incurs a performance-hit and should be avoided

Any input is appreciated - thanks!

**Comment by pruiz** [comment]
Hi,

Well MultiplexingConverter is not supposed to be thread-safe (ie. used [concurrently] by one or more threads) by itself, however, you can use as many 'MultiplexingConverter' instances as you want/need from each thread. And those instances (internally) will take care of multiplexing access to the shared wkhtmltox native engine under the hood.

Maybe the naming was a bit confusing on my part.. :?

**Comment by JulianMay** [comment]
Ok, thanks for clarifying 👍
