### ISSUE TITLE
Page size?

### ISSUE THREAD

**Issue by hahmed** [pruiz/WkHtmlToXSharp#6]
I was wondering how do I set the page width/size?
 
WkhtmlToPDF (according to http://madalgo.au.dk/~jakobt/wkhtmltoxdoc/wkhtmltopdf-0.9.9-doc.html)
 
Exposes the option –-page-width

**Comment by pruiz** [comment]
I just published a new version (1.2.5+) supporting PageSize properties (from a pull-req from @tomdenny), so I am closing this issue too.
