### ISSUE TITLE
Poor performance from ASP.NET MVC application

### ISSUE THREAD

**Issue by tjaskula** [pruiz/WkHtmlToXSharp#8]
Hi,

I encounter a poor perfomrance issue (1 minute for PDF generation of simple html page, no concurrent requests) while using WkHTMLToXSharp from whitin a ASP.NET MVC 3 application and .NET framework 4.0. I'm using a MultiplexingConverter like in the example below :

var wk = new MultiplexingConverter();
wk.GlobalSettings.Margin.Top = "0cm";
wk.GlobalSettings.Margin.Bottom = "0cm";
wk.GlobalSettings.Margin.Left = "0cm";
wk.GlobalSettings.Margin.Right = "0cm";

wk.ObjectSettings.Web.EnablePlugins = false;
wk.ObjectSettings.Web.EnableJavascript = false;
wk.ObjectSettings.Page = url;

wk.ObjectSettings.Load.Proxy = "none";

Do you have any hints, what's going on or how can I debug/improve it ?

Thanks,

**Comment by dobragab** [comment]
Hello,

I've got the same issue as rbkaranam. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. 

VS 2013 and c# Windows Forms Application.

Also this issue:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1542

using Bookman Old Style...

**Comment by pruiz** [comment]
Running this library under ASP.NET (or more specifically IIS) is not supported. This has to do with the way IIS manages underlaying threads, and application pools.

What most people do (myself included) is to create a daemon or windows service which handles requests from the ASP.NET/MVC/etc. process via any form of RPC or queuing.

Regards
